"""Add verified field to DraftReconciliationEntry

Revision ID: 20c47b00128e
Revises: 119b9dd99c10
Create Date: 2025-03-04 09:19:42.850459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20c47b00128e'
down_revision: Union[str, None] = '119b9dd99c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('draft_reconciliation_entries')]
    
    if 'verified' not in columns:
        op.add_column('draft_reconciliation_entries', 
                     sa.Column('verified', sa.Boolean(), 
                              server_default=sa.text('false'), 
                              nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_reconciliation_entries', 'verified')
    # ### end Alembic commands ###
