"""create bank reconciliation table

Revision ID: 850225ab9759
Revises: adc109e11fc5
Create Date: 2024-12-17 12:46:12.381263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '850225ab9759'
down_revision: Union[str, None] = 'adc109e11fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('payee', sa.String(), nullable=False),
    sa.Column('particulars', sa.String(), nullable=False),
    sa.Column('spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('received', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('insert_time', sa.Date(), nullable=False),
    sa.Column('inserted_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_reconciliation')
    # ### end Alembic commands ###
