"""add_last_successful_login_column

Revision ID: adc109e11fc5
Revises: a080bf2fc295
Create Date: 2024-12-03 10:25:35.918740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc109e11fc5'
down_revision: Union[str, None] = 'a080bf2fc295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_successful_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_successful_login')
    # ### end Alembic commands ###
