"""add xero state table

Revision ID: d6f2814aaf75
Revises: c75d53b27276
Create Date: 2025-02-17 12:49:32.380269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd6f2814aaf75'
down_revision: Union[str, None] = 'c75d53b27276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xero_states',
        sa.Column('state', sa.String(), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_xero_states_state'), 'xero_states', ['state'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xero_states_state'), table_name='xero_states')
    op.drop_table('xero_states')
    # ### end Alembic commands ###
