"""add new columns to bank reconciliation

Revision ID: d8451148daa7
Revises: 850225ab9759
Create Date: 2024-12-17 14:00:48.697508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8451148daa7'
down_revision: Union[str, None] = '850225ab9759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_reconciliation', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('bank_reconciliation', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('bank_reconciliation', sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bank_reconciliation', sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bank_reconciliation', sa.Column('details', sa.String(), nullable=True))
    op.add_column('bank_reconciliation', sa.Column('name_ref', sa.String(), nullable=True))
    op.add_column('bank_reconciliation', sa.Column('exact_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_reconciliation', 'exact_amount')
    op.drop_column('bank_reconciliation', 'name_ref')
    op.drop_column('bank_reconciliation', 'details')
    op.drop_column('bank_reconciliation', 'max_amount')
    op.drop_column('bank_reconciliation', 'min_amount')
    op.drop_column('bank_reconciliation', 'end_date')
    op.drop_column('bank_reconciliation', 'start_date')
    # ### end Alembic commands ###
