"""Update DraftReconciliationEntry

Revision ID: fcca895c318d
Revises: 20c47b00128e
Create Date: 2025-03-04 10:54:09.180404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcca895c318d'
down_revision: Union[str, None] = '20c47b00128e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_reconciliation_entries', sa.Column('statement_id', sa.String(), nullable=False))
    op.add_column('draft_reconciliation_entries', sa.Column('invoice_id', sa.String(), nullable=True))
    op.add_column('draft_reconciliation_entries', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_reconciliation_entries', 'notes')
    op.drop_column('draft_reconciliation_entries', 'invoice_id')
    op.drop_column('draft_reconciliation_entries', 'statement_id')
    # ### end Alembic commands ###
